### ISSUE TITLE
Annoying flickering when delete

### ISSUE THREAD

**Issue by EvgeniyRRU** [yuanqing/malarkey#11]
There is a some annoying flickering effect when element content deletes. I prepared [codepen](http://codepen.io/EvgeniyRRU/pen/PzVAAX) for you. It can be easy fixed by css:

``` css
.malarkey {
    min-height: 20px;
}
```

But is it possible to implement this feature out of the box? Thank you.
